/**
 * 커뮤니티 한국어 카피 — 한 곳에서 관리한다.
 * 톤: 기존 대시보드와 일관되게 간결한 존댓말("~해요/~하세요").
 */
export const COMMUNITY_COPY = {
  nav: {
    community: '커뮤니티',
    simulator: '시뮬레이터',
    toSimulator: '시뮬레이터로',
    write: '글쓰기',
    home: 'Snowball',
    login: '로그인',
    logout: '로그아웃',
    myScenarios: '내 시나리오'
  },
  gallery: {
    mainLabel: '시나리오 목록',
    sortAriaLabel: '정렬 기준',
    sortRecent: '최신',
    sortPopular: '인기',
    viewCard: '카드 보기',
    viewInline: '목록 보기',
    metaViews: '조회수',
    metaLikes: '좋아요',
    metaComments: '댓글',
    simBadge: '시뮬 결과',
    loadingMore: '더 불러오는 중…',
    reachedEnd: '마지막 시나리오입니다',
    emptyTitle: '아직 공유된 시나리오가 없어요',
    emptySubtitle: '첫 번째 시나리오를 공유해보세요.',
    emptyCta: '글쓰기',
    searchEmptyTitle: (query: string) => `'${query}'에 대한 결과가 없어요`,
    searchEmptySubtitle: '다른 검색어나 필터를 사용해보세요.',
    searchEmptyCta: '검색 초기화',
    errorTitle: '목록을 불러오지 못했어요',
    errorBody: '잠시 후 다시 시도해주세요.',
    retry: '다시 시도',
    searchPlaceholder: '시나리오 검색',
    searchAriaLabel: '시나리오 검색',
    searchFilterAriaLabel: '검색 필터'
  },
  write: {
    titleNew: '시나리오 공유',
    titleEdit: '시나리오 수정',
    fieldTitle: '제목',
    fieldBody: '내용',
    fieldDescription: '요약(선택)',
    fieldVisibility: '공개 범위',
    fieldAttachment: '시뮬레이션 첨부',
    bodyAriaLabel: '내용',
    toolbarAriaLabel: '서식',
    bold: '굵게',
    italic: '기울임',
    heading2: '제목',
    heading3: '소제목',
    bulletList: '글머리 목록',
    orderedList: '번호 목록',
    link: '링크',
    linkUrlPlaceholder: 'https://',
    linkApply: '적용',
    linkRemove: '해제',
    descriptionPlaceholder: '목록에 보일 한 줄 소개. 비우면 본문 앞부분을 자동으로 사용해요.',
    bodyPlaceholder: '어떤 전략인지, 왜 이렇게 구성했는지 적어보세요.',
    visibilityPublic: '공개 — 커뮤니티 갤러리에 노출돼요.',
    visibilityPrivate: '비공개 — 나만 볼 수 있어요.',
    attachEmpty: '현재 시뮬레이터에 설정한 시나리오를 함께 첨부할 수 있어요.',
    attachButton: '현재 시뮬레이션 첨부',
    attachDetach: '해제',
    attachTickerCount: (count: number) => `티커 ${count}개`,
    submitNew: '게시',
    submitEdit: '수정 완료',
    cancel: '취소',
    loginGateTitle: '로그인하고 시나리오를 공유하세요',
    loginGateSubtitle: '로그인하면 시나리오를 공유하고 좋아요·댓글을 남길 수 있어요.',
    counter: (current: number, max: number) => `${current}/${max}`,
    errorTitleRequired: '제목을 입력해주세요.',
    errorTitleTooLong: '제목은 80자까지 쓸 수 있어요.',
    errorBodyRequired: '내용이나 시뮬레이션 중 하나는 있어야 해요.',
    errorBodyTooLong: '내용이 너무 길어요. 조금 줄여주세요.',
    errorBodyTooLarge: '내용이 너무 길어요. 서식이나 길이를 줄여주세요.',
    issueTooManyTickers: '티커가 너무 많아요. 최대 50개까지 첨부할 수 있어요.',
    issuePayloadTooLarge: '시나리오 데이터가 너무 커요. 티커 수나 본문을 줄여주세요.',
    issueMissingSettings: '시뮬레이션 설정이 비어 있어요. 시뮬레이터에서 먼저 구성해주세요.',
    saveFailed: '게시에 실패했어요. 잠시 후 다시 시도해주세요.',
    leaveConfirmTitle: '작성 중인 내용이 있어요',
    leaveConfirmBody: '나가면 사라져요.',
    leaveConfirmStay: '계속 작성',
    leaveConfirmLeave: '나가기',
    toastPublished: '게시했어요',
    toastSaved: '저장했어요'
  },
  detail: {
    mainLabel: '시나리오 상세',
    attachCtaTitle: '이 시나리오로 시뮬레이션 열기',
    attachCtaButton: '시뮬레이터에서 열어보기',
    edit: '수정',
    delete: '삭제',
    deleteConfirmTitle: '이 시나리오를 삭제할까요?',
    deleteConfirmBody: '되돌릴 수 없어요.',
    deleteConfirm: '삭제',
    deleteCancel: '취소',
    likeAria: '좋아요',
    likeActiveAria: '좋아요 취소',
    notFoundTitle: '시나리오를 찾을 수 없어요',
    notFoundCta: '목록으로',
    errorTitle: '시나리오를 불러오지 못했어요',
    errorBody: '잠시 후 다시 시도해주세요.',
    retry: '다시 시도',
    toastDeleted: '삭제했어요'
  },
  comments: {
    sectionLabel: '댓글',
    heading: (count: number) => `댓글 ${count}`,
    placeholder: '댓글을 남겨보세요.',
    reply: '답글',
    submit: '등록',
    deletedPlaceholder: '삭제된 댓글입니다',
    empty: '첫 댓글을 남겨보세요.',
    loginPrompt: '댓글을 쓰려면 로그인하세요',
    deleteConfirmTitle: '댓글을 삭제할까요?',
    deleteConfirm: '삭제',
    deleteCancel: '취소',
    delete: '삭제',
    errorTitle: '댓글을 불러오지 못했어요',
    retry: '다시 시도',
    like: '좋아요'
  },
  login: {
    title: '로그인',
    subtitle: '로그인하면 시나리오를 공유하고 좋아요·댓글을 남길 수 있어요.',
    google: 'Google로 계속하기',
    kakao: '카카오로 계속하기',
    close: '닫기'
  },
  common: {
    close: '닫기',
    genericError: '잠시 후 다시 시도해주세요.'
  }
} as const;
