/**
 * 커뮤니티 한국어 카피 — 한 곳에서 관리한다.
 * 톤: 기존 대시보드와 일관되게 간결한 존댓말("~해요/~하세요").
 */
export const COMMUNITY_COPY = {
  nav: {
    community: '커뮤니티',
    simulator: '시뮬레이터',
    toSimulator: '시뮬레이터로',
    write: '글쓰기',
    home: 'Snowball',
    login: '로그인',
    logout: '로그아웃',
    theme: '테마',
    // ── 전역 nav(PrimaryNav) — 브랜드 링크 + 라우트 링크(시뮬레이터·갤러리·게시판) ──
    /** nav 랜드마크 이름(<nav aria-label>). */
    primaryLabel: '주요 메뉴',
    /** 브랜드 워드마크(로고+앱이름 링크). "Snowball Income" 워드마크 유지. */
    brand: 'Snowball Income',
    /** 커뮤니티 갤러리 링크(/community). */
    gallery: '포트폴리오 갤러리',
    /** 자유게시판 링크(/community/board). */
    board: '게시판',
    /** 상세/글쓰기 하위에서 목록으로 복귀하는 뒤로가기 라벨. */
    list: '목록'
  },
  gallery: {
    mainLabel: '시나리오 목록',
    sortAriaLabel: '정렬 기준',
    sortRecent: '최신',
    sortPopular: '인기',
    viewCard: '카드 보기',
    viewInline: '목록 보기',
    metaViews: '조회수',
    metaLikes: '좋아요',
    metaComments: '댓글',
    simBadge: '시뮬 결과',
    loadingMore: '더 불러오는 중…',
    reachedEnd: '마지막 시나리오입니다',
    emptyTitle: '아직 공유된 시나리오가 없어요',
    emptySubtitle: '첫 번째 시나리오를 공유해보세요.',
    emptyCta: '글쓰기',
    searchEmptyTitle: (query: string) => `'${query}'에 대한 결과가 없어요`,
    searchEmptySubtitle: '다른 검색어나 필터를 사용해보세요.',
    searchEmptyCta: '검색 초기화',
    errorTitle: '목록을 불러오지 못했어요',
    errorBody: '잠시 후 다시 시도해주세요.',
    retry: '다시 시도',
    searchPlaceholder: '포트폴리오 검색',
    searchAriaLabel: '포트폴리오 검색',
    searchFilterAriaLabel: '검색 필터',

    // ── 정밀 검색(PrecisionSearch) — 트리거·패널·필드·빈결과 (단일 원천) ──
    filterTitle: '정밀 검색',
    filterTriggerAria: '정밀 검색',
    filterActiveCountAria: (n: number) => `적용된 필터 ${n}개`,
    filterClose: '닫기',

    filterMonthlyLabel: '월 배당(세후)',
    filterMonthlyMinAria: '월 배당 최소',
    filterMonthlyMaxAria: '월 배당 최대',
    filterMonthlyHint: '세후 월 배당 기준이에요.',

    filterTargetLabel: '목표 월 배당',
    filterTargetMinAria: '목표 월 배당 이상',
    filterTargetSuffix: '이상',

    filterDurationLabel: '투자 기간',
    filterDurationMinAria: '투자 기간 최소',
    filterDurationMaxAria: '투자 기간 최대',

    // 티커(TICKER_FILTER_ENABLED=true 될 때만 사용 — 미리 정의)
    filterTickerLabel: '종목(티커)',
    filterTickerAria: '종목 티커',
    filterTickerPlaceholder: '티커 검색 (예: SCHD)',

    unitManwon: '만원',
    unitYear: '년',

    filterApply: '적용',
    filterReset: '초기화',
    filterRangeError: '최솟값이 최댓값보다 클 수 없어요.',

    // filteredEmpty 빈상태
    filterEmptyTitle: '조건에 맞는 시나리오가 없어요',
    filterEmptySubtitle: '검색어나 필터를 바꿔보세요.',
    filterEmptyCta: '필터 초기화'
  },
  board: {
    // 자유게시판(질문·고민·잡담·건의·뉴스·의견 자유글) — 평면 게시판(카테고리 탭 없음), 최신순.
    mainLabel: '자유게시판',
    title: '자유게시판',
    subtitle: '질문·고민·잡담·건의·뉴스, 무엇이든 자유롭게 이야기해요.',
    write: '글쓰기',
    loadingMore: '더 불러오는 중…',
    reachedEnd: '마지막 글이에요',
    emptyTitle: '아직 글이 없어요',
    emptySubtitle: '첫 글을 남겨보세요.',
    emptyCta: '글쓰기',
    errorTitle: '게시판을 불러오지 못했어요',
    errorBody: '잠시 후 다시 시도해주세요.',
    retry: '다시 시도'
  },
  write: {
    titleNew: '시나리오 공유',
    titleEdit: '시나리오 수정',
    // 자유게시판 글쓰기/수정(같은 폼 재사용, kind='board') — 시나리오 공유가 아니라 자유글이다.
    titleNewBoard: '새 글 쓰기',
    titleEditBoard: '글 수정',
    /** 게시판 본문 플레이스홀더 — 전략 설명이 아니라 자유 주제. */
    bodyPlaceholderBoard: '자유롭게 이야기를 남겨보세요.',
    fieldTitle: '제목',
    fieldBody: '내용',
    fieldAttachment: '시뮬레이션',
    bodyAriaLabel: '내용',
    toolbarAriaLabel: '서식',
    bold: '굵게',
    italic: '기울임',
    underline: '밑줄',
    strike: '취소선',
    inlineCode: '인라인 코드',
    heading2: '제목',
    heading3: '소제목',
    blockquote: '인용',
    codeBlock: '코드 블록',
    bulletList: '글머리 목록',
    orderedList: '번호 목록',
    horizontalRule: '구분선',
    undo: '실행 취소',
    redo: '다시 실행',
    link: '링크',
    linkUrlPlaceholder: 'https://',
    linkApply: '적용',
    linkRemove: '해제',
    /**
     * 툴바 버튼 title(툴팁)에 붙는 단축키 힌트. 접근명(aria-label)은 위 라벨 그대로 두고,
     * 툴팁에만 "굵게 (Ctrl+B)" 형태로 합쳐 보여준다.
     */
    shortcutBold: 'Ctrl+B',
    shortcutItalic: 'Ctrl+I',
    shortcutUnderline: 'Ctrl+U',
    shortcutStrike: 'Ctrl+Shift+S',
    shortcutInlineCode: 'Ctrl+E',
    shortcutHeading2: 'Ctrl+Alt+2',
    shortcutHeading3: 'Ctrl+Alt+3',
    shortcutBlockquote: 'Ctrl+Shift+B',
    shortcutCodeBlock: 'Ctrl+Alt+C',
    shortcutBulletList: 'Ctrl+Shift+8',
    shortcutOrderedList: 'Ctrl+Shift+7',
    shortcutUndo: 'Ctrl+Z',
    shortcutRedo: 'Ctrl+Shift+Z',
    /** 툴바 그룹(role=group) 접근명 — 버튼이 늘어 줄바꿈되므로 그룹으로 묶어 탐색을 돕는다. */
    toolbarGroupInline: '글자 서식',
    toolbarGroupBlock: '문단 서식',
    toolbarGroupList: '목록',
    toolbarGroupInsert: '삽입',
    toolbarGroupHistory: '실행 이력',
    bodyPlaceholder: '어떤 전략인지, 왜 이렇게 구성했는지 적어보세요.',
    visibilityPublic: '공개 — 커뮤니티 갤러리에 노출돼요.',
    visibilityPrivate: '비공개 — 나만 볼 수 있어요.',
    sectionPublish: '게시 설정',
    bodyOrAttachHint: '내용과 시뮬레이션 중 하나만 있어도 게시할 수 있어요.',
    /** 게시판(kind='board')은 시뮬 첨부가 없어 본문이 필수다 — 위 힌트(첨부 대체 가능)를 쓰면 거짓말이 된다. */
    bodyRequiredHintBoard: '제목과 내용을 입력하면 게시할 수 있어요.',
    attachSectionHint: '첨부하면 읽는 사람이 내 포트폴리오와 투자 설정을 시뮬레이터에서 그대로 열어볼 수 있어요.',
    attachToggleLabel: '첨부',
    attachPickerHeading: '첨부할 시나리오를 고르세요. 고르는 즉시 붙어요.',
    attachPickerGroupLabel: '첨부할 시나리오',
    attachOptionUnavailable: '첨부할 수 없어요',
    attachEmptyTitle: '아직 첨부할 시뮬레이션이 없어요',
    attachEmptyBody: '메인 화면에서 포트폴리오와 투자 설정을 만들면 여기에서 바로 첨부할 수 있어요.',
    attachEmptyCta: '시뮬레이터로 가기',
    attachedHint: '첨부 시점의 설정이 저장돼요. 게시하면 읽는 사람이 시뮬레이터에서 그대로 열어볼 수 있어요.',
    attachTickerCount: (count: number) => `티커 ${count}개`,
    submitNew: '게시',
    submitEdit: '수정 완료',
    cancel: '취소',
    loginGateTitle: '로그인하고 시나리오를 공유하세요',
    loginGateSubtitle: '로그인하면 시나리오를 공유하고 좋아요·댓글을 남길 수 있어요.',
    counter: (current: number, max: number) => `${current}/${max}`,
    errorTitleRequired: '제목을 입력해주세요.',
    errorTitleTooLong: '제목은 80자까지 쓸 수 있어요.',
    errorBodyRequired: '내용이나 시뮬레이션 중 하나는 있어야 해요.',
    errorBodyTooLong: '내용이 너무 길어요. 조금 줄여주세요.',
    errorBodyTooLarge: '내용이 너무 길어요. 서식이나 길이를 줄여주세요.',
    issueTooManyTickers: '티커가 너무 많아요. 최대 50개까지 첨부할 수 있어요.',
    issuePayloadTooLarge: '시나리오 데이터가 너무 커요. 티커 수나 본문을 줄여주세요.',
    issueMissingSettings: '시뮬레이션 설정이 비어 있어요. 시뮬레이터에서 먼저 구성해주세요.',
    saveFailed: '게시에 실패했어요. 잠시 후 다시 시도해주세요.',
    leaveConfirmTitle: '작성 중인 내용이 있어요',
    leaveConfirmBody: '나가면 사라져요.',
    leaveConfirmStay: '계속 작성',
    leaveConfirmLeave: '나가기'
  },
  detail: {
    mainLabel: '시나리오 상세',
    attachCtaTitle: '이 시나리오로 시뮬레이션 열기',
    attachCtaButton: '시뮬레이터에서 열어보기',
    previewTitle: '시나리오 미리보기',
    previewChartLabel: '포트폴리오 비중',
    edit: '수정',
    delete: '삭제',
    deleteConfirmTitle: '이 시나리오를 삭제할까요?',
    deleteConfirmBody: '되돌릴 수 없어요.',
    deleteConfirm: '삭제',
    deleteCancel: '취소',
    likeAria: '좋아요',
    likeActiveAria: '좋아요 취소',
    notFoundTitle: '시나리오를 찾을 수 없어요',
    notFoundCta: '목록으로',
    errorTitle: '시나리오를 불러오지 못했어요',
    errorBody: '잠시 후 다시 시도해주세요.',
    retry: '다시 시도'
  },
  comments: {
    sectionLabel: '댓글',
    heading: (count: number) => `댓글 ${count}`,
    placeholder: '댓글을 남겨보세요.',
    reply: '답글',
    submit: '등록',
    deletedPlaceholder: '삭제된 댓글입니다',
    empty: '첫 댓글을 남겨보세요.',
    loginPrompt: '댓글을 쓰려면 로그인하세요',
    deleteConfirmTitle: '댓글을 삭제할까요?',
    deleteConfirm: '삭제',
    deleteCancel: '취소',
    delete: '삭제',
    errorTitle: '댓글을 불러오지 못했어요',
    retry: '다시 시도',
    submitFailed: '댓글을 등록하지 못했어요. 잠시 후 다시 시도해 주세요.',
    deleteFailed: '댓글을 삭제하지 못했어요. 잠시 후 다시 시도해 주세요.',
    likeFailed: '좋아요 처리에 실패했어요. 잠시 후 다시 시도해 주세요.',
    loadMore: '더 보기',
    loadingMore: '더 불러오는 중…'
  },
  profile: {
    menuItem: '프로필 설정',
    title: '프로필 설정',
    loading: '불러오는 중…',
    loginGateTitle: '로그인하고 프로필을 관리하세요',
    loginGateSubtitle: '커뮤니티에 표시될 닉네임을 바꾸고, 계정을 관리할 수 있어요.',
    accountSectionLabel: '내 계정',
    nicknameLabel: '닉네임',
    nicknameHint: '2~20자. 커뮤니티 글과 댓글에 표시돼요.',
    nicknameSave: '저장',
    nicknameSaved: '닉네임을 바꿨어요. 이전에 쓴 글에도 새 닉네임이 보여요.',
    errorNicknameLength: '닉네임은 2~20자로 입력해주세요.',
    errorNicknameNetwork: '닉네임을 저장하지 못했어요. 잠시 후 다시 시도해주세요.',
    errorSessionExpired: '로그인이 만료됐어요. 다시 로그인한 뒤 시도해주세요.',
    dangerTitle: '회원 탈퇴',
    dangerBody: '계정과 함께 작성한 글·댓글·좋아요가 모두 삭제돼요. 되돌릴 수 없어요.',
    dangerCta: '회원 탈퇴',
    deleteTitle: '정말 탈퇴할까요?',
    deleteScopeIntro: '아래 데이터가 모두 삭제돼요:',
    deleteScopeItems: [
      '프로필과 계정 정보',
      '작성한 글 전부 (첨부한 시뮬레이션 포함)',
      '작성한 댓글 전부 — 내 댓글에 달린 다른 사람의 답글도 함께 삭제돼요',
      '좋아요 기록'
    ],
    deleteIrreversible: '삭제한 데이터는 되돌릴 수 없어요.',
    deleteConfirmInstruction: "계속하려면 '탈퇴'를 입력해주세요.",
    deleteConfirmLabel: '탈퇴 확인 입력',
    deleteConfirmWord: '탈퇴',
    deleteCancel: '취소',
    deleteExecute: '영구 삭제',
    deleteFailed: '탈퇴를 완료하지 못했어요. 계정은 그대로 남아 있어요. 잠시 후 다시 시도해주세요.',
    deleteDone: '탈퇴가 완료됐어요. 그동안 함께해주셔서 감사합니다.',
    deleteDoneDismiss: '닫기'
  },
  login: {
    title: '로그인',
    subtitle: '로그인하면 시나리오를 공유하고 좋아요·댓글을 남길 수 있어요.',
    // 구글 규정 "Continue with Google"의 한국어 표준 표기(공식체). 4개 진입점(로그인 모달·내 저장·글쓰기 게이트·프로필 게이트) 공통 정본.
    google: 'Google 계정으로 계속하기',
    kakao: '카카오로 계속하기',
    // 네이버: 컴포넌트 로컬 상수였던 것을 정본으로 승격.
    naver: '네이버로 계속하기',
    naverPending: '네이버 로그인은 준비 중이에요. 지금은 구글 또는 카카오로 로그인해 주세요.',
    naverPendingBadge: '준비 중',
    // 네이버 앱 심사(검수) 통과 전 상태 — env 는 설정됐지만 authorize 가 아직 승인 전이라 실패한다.
    naverReview: '네이버 로그인은 심사 중이에요. 승인되면 바로 열려요. 지금은 구글 또는 카카오로 로그인해 주세요.',
    naverReviewBadge: '검수중',
    // 네이버 authorize 에서 되돌아온 콜백 경로가 세션 교환 중 잠깐 보이는 안내(main.tsx completeNaverCallback).
    naverCallback: '네이버 로그인 처리 중…'
  },
  common: {
    close: '닫기',
    genericError: '잠시 후 다시 시도해주세요.'
  }
} as const;
