export {
  AllocationChartLayout,
  AllocationClearFixedButton,
  AllocationColorDot,
  AllocationFixButton,
  AllocationHint,
  AllocationHoldingAmount,
  AllocationHoldingBasis,
  AllocationHoldingDivider,
  AllocationHoldingDividend,
  AllocationHoldingField,
  AllocationHoldingNotice,
  AllocationHoldingRow,
  AllocationHoldingTotal,
  AllocationHoldingTotalLabel,
  AllocationLegend,
  AllocationLegendColumn,
  AllocationLegendItem,
  AllocationLegendName,
  AllocationLegendSlider,
  AllocationLegendValue,
  AllocationSrOnly,
  SelectedChipWrap
} from './PortfolioAllocation.styled';
